name: Point Features ETL Pipeline

on:
  # Run on schedule (daily at 00:00 UTC)
  schedule:
    - cron: '0 0 * * *'
  
  # Run manually from GitHub Actions tab
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches:
      - main
    paths:
      - '.github/workflows/etl/**'
      - '.github/workflows/et-pipeline.yml'

jobs:
  run-point-features-etl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install Python dependencies
      working-directory: .github/workflows/etl
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas python-dotenv supabase pytest pathlib
    
    - name: Run Point Features ETL Pipeline
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      working-directory: .github/workflows/etl
      run: |
        python main.py
    
    - name: Handle Success
      if: success()
      run: |
        echo "Point Features ETL pipeline completed successfully!"
    
    - name: Handle Failure
      if: failure()
      run: |
        echo "Point Features ETL pipeline failed!"
        exit 1 